core/urls.py
from django.urls import path

from core import views



app_name = 'jobs'

urlpatterns = [
    path('<int:pk>/',  views.job_detail, name='jobs'),
    path('create/', views.create_job, name='create_job'),
    path('update/<int:pk>', views.update_job, name='update_job'),
    path('job_list/', views.job_list, name='job_list'),
    path('delete/<int:pk>', views.delete_job, name='delete_job'),
    #path('schedule/view/<int:job_id>', views.job_schedule_view, name='job_schedule'),
    #path('schedule/add/<int:job_id>', views.add_job_schedule, name='add_schedule'),
    #path('schedule/update/<int:pk>', views.update_schedule, name='update_schedule'),
    #path('schedule/delete/<int:pk>', views.delete_schedule, name='delete_schedule'),
     
     
]

orders/urls.py
# urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
    path('add/', create_order, name='create_order'),
    path('delete/<int:pk>/', delete_order, name='delete_order'),
    path('update/<int:pk>/', update_order, name='update_order'),
    path('order_list/', order_list, name='order_list'),
    path('<int:pk>/', order_detail, name='order_detail'),
]

rest/urls.py
import statistics
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from core.views import index
from members.views import login_user, logout_user
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name ='index'),
    path('clients/', include('clients.urls')),
    path('employees/',include('employees.urls'), name ='employees'),
    path('jobs/', include('core.urls'), name ='jobs'),  
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('inventory/', include('inventory.urls'), name ='inventory'),   
    path('orders/', include('orders.urls'), name ='orders'), 
    path('maintenance/', include('maintenance.urls'), name ='maintenance'),
    

   
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from datetime import date, timedelta
from django.utils.translation import gettext_lazy as _
from core.models import Job 
from inventory.models import *


    

class Order(models.Model):
    class OrderStatus(models.TextChoices):
        OPEN = 'OP',_('Open')
        CLOSED = 'CL', _('Closed')
    class Type(models.TextChoices):
        BATTERY = 'BA', _('Battery')
        INVERTER = 'IN', _('Inverter')
        PANEL = 'PN', _('Panel')
    brand_name=models.ForeignKey(Brand, on_delete=models.CASCADE, related_name= "order_brands")
    type= models.CharField(
        max_length=2,
        choices=Type.choices,
        default=Type.BATTERY,
    )
    model=models.CharField(max_length=255, default =0, blank=True, null=True)
    size = models.CharField(max_length=255, default =0, blank=True, null=True)
    quantity = models.IntegerField(default =0,blank=True, null=True)
    cost=models.IntegerField(default =0,blank=True, null=True)
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name= "job",default=None,blank=True, null=True)
    notes=models.TextField(default=None,blank=True, null=True)
    order_date=models.DateField( default=date.today)
    due_date=models.DateField(default=None,blank=True, null=True)
    date_received=models.DateField(default=None,blank=True, null=True)
    order_status= models.CharField(
        max_length=2,
        choices=OrderStatus.choices,
        default=OrderStatus.OPEN,
    )
    def __str__(self):
        return self.brand_name.name+' '+self.model
    

orders/forms.py
from django import forms
from django.forms import FileInput, ModelForm, TextInput
from .models import Order

class OrderCreationForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'  # Add other fields as needed
        widgets = {
            'order_date': forms.DateInput(attrs={'class': 'datepicker'}),
            'due_date': forms.DateInput(attrs={'class': 'datepicker'}),
            'date_received': forms.DateInput(attrs={'class': 'datepicker'}),
        
        }

orders/views.py
from django.shortcuts import get_object_or_404, render, redirect
from orders.forms import OrderCreationForm
from .models import Order
from core.filters import OrderFilter
from django.contrib import messages
# Create your views here.

def create_order(request):
    if request.method == 'POST':
        order_form = OrderCreationForm(request.POST)
        if order_form.is_valid():

            order_form.save()
            return redirect('orders:order_list')  # Redirect to the homepage after successful form submission
        else:
            messages.success(request,("There was an error, serial number already exists"))
            return redirect('orders:create_order') 
    else:
        order_filter = OrderFilter(request.GET, queryset=Order.objects.all())
        search_form=order_filter.form
        orders = order_filter.qs
        order_form = OrderCreationForm()
        context = {'orders': orders, 'search_form': search_form, 'order_form': order_form}
        
        return render(request, 'create_order.html', context)
    
def update_order(request, pk):
    orders=Order.objects.get(pk=pk)
    form = OrderCreationForm(instance=orders)
    if request.method == 'POST':
        form = OrderCreationForm(request.POST, request.FILES, instance=orders)
    context= {'order_form': form}
    if form.is_valid():
            form.save()
            return redirect('orders:create_order')  # Redirect to the order list page
    else:
        form = OrderCreationForm()
    
    return render(request, 'create_order.html', context)


def delete_order(request, pk):
    order=Order.objects.get(pk=pk)
    if request.method == 'POST':
        order.delete()
        return redirect('order_list') 
    
    context = {'item': order}
    return render(request, 'delete_order.html', context)

def order_list(request):
    order_filter = OrderFilter(request.GET, queryset=Order.objects.all())
    form=order_filter.form
    orders = order_filter.qs
    return render(request, 'order_list.html', {'orders': orders, 'form': form})

def order_detail(request, pk):
    orders = get_object_or_404(Order, pk=pk)

    context = {'order':orders}

    return render(request, 'order_detail.html', context) 

   

orders/templates/create_order.html
{% extends 'core/base.html' %}
{% load tailwind_filters %}
{% block content %}

<h2 class="text-center mb-4 text-xl font-bold leading-none tracking-tight text-white md:text-2xl lg:text-3xl dark:text-white">Add/Update Order</h2>
  
<div class="mx-auto w-4/12 bg-yellow-400 p-7 my-10 ">
  <form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ order_form|crispy }}
  
    <button class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800 mt-5" type="submit">Create/Update Schedule</button>
  </form>

</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        flatpickr('.datepicker', {
            dateFormat: 'Y-m-d',
        });
    });
</script>

{% endblock %}

orders/templates/delete_order.html
{% extends 'core/base.html' %}
{% load tailwind_filters %}
{% load static %}
{% block content %}

<p class="text-2xl text-white">Are you sure you want to delete "{{item}}" ?</p>

<form action="{% url 'orders:delete_order' item.id %} " method ='POST' class="text-white mt-10 px-10">

    {% csrf_token %}
    
    <a href="{% url 'orders:order_list' %}"class="px-3 py-2 text-white no-underline bg-emerald-700 rounded hover:bg-emerald-500 text-sm">Cancel</a>

    <input class="px-3 py-2 text-white no-underline bg-red-800 rounded hover:bg-red-600 text-sm" type="submit" name="Confirm">


</form>


{% endblock %}

orders/templates/order_detail.html
{% extends 'core/base.html'%}

{% block title %} {{order}} {{order.get_type_display}}{% endblock %}

{% block content %}
{% load static %}
{% load mathfilters %}

<div class="grid grid-cols-5 gap-6">

   

<div class="bg-white col-span-3 p-6 max-w-2xl shadow overflow-hidden sm:rounded-lg">
    <div class="px-4 py-5 sm:px-6">
        <h3 class="text-lg leading-6 font-medium text-gray-900">
            {{order}} {{order.get_type_display}}
        </h3>
        <p class="mt-1 max-w-2xl text-sm text-gray-500">
            Details and informations about order.
        </p>
    </div>
    <div class="border-t border-gray-200">
        <dl>
            
            <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Order Info
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{order.brand_name}}
                </dd>
            </div>
            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Model Info
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{order.model}}
                </dd>
            </div>
            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Quantity Info
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{order.quantity}}
                </dd>
            </div>
            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Due Date
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{order.due_date}}
                </dd>
            </div>
            
        </dl>
        <div class ="mt-10">
            <a href="{% url 'orders:update_order' order.id%}"
              class="px-3 py-2 text-white no-underline bg-emerald-700 rounded hover:bg-emerald-500 text-sm ">Update Order</a>
            </div>
            <div class ="mt-10" >
          <a href="#" class="px-3 py-2 text-white no-underline bg-red-700 rounded hover:bg-red-500 text-sm"> Delete</a>
         </div> 
    </div>
</div>
{% endblock %} 

orders/templates/order_list.html
{% extends 'core/base.html' %}
{% load tailwind_filters %}

{% block content %}

<div class="mb-10 grid-cols-2">
<h1 class="text-white text-3xl text-center" >Orders List</h1>

</div>
<div class="mt-10 auto-cols-max text-left">
  <div class ="text-center">
     <a href="{% url 'orders:create_order' %}" class="px-6 py-3 text-white no-underline bg-emerald-700 rounded hover:emerald-700 hover:underline hover:text-blue-200 ">Add new orders</a>
  </div>
  <div class="mx-auto w-4/12 bg-yellow-400 p-7 my-10 col-3">
      <form method="GET" action ="{% url 'orders:order_list' %}">
      {{ form|crispy }}
      <button type="submit" class="mt-5 text-white bg-red-700 hover:bg-red-800 focus:outline-none focus:ring-4 focus:ring-red-300 font-medium rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">Search</button></td>
      </form>
  </div>
</div>

<div class="relative overflow-x-auto">
    <table class=" table w-full text-md text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-sm text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
  
    <tr>
      <th scope="col" class="px-6 py-3">orders Status</th>
      <th scope="col" class="px-6 py-3">orders Brand</th>
      <th scope="col" class="px-6 py-3">orders Model</th>
      <th scope="col" class="px-6 py-3">orders Quantity</th>
      <th scope="col" class="px-6 py-3">Order Details</th>
      <th scope="col" class="px-6 py-3">Remove</th>
    </tr>
    {% for orders in orders %}
    <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
      <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
      
      {{ orders.status }}</th>
      <td>{{ orders.brand_name }}</td>
      <td>{{ orders.model }}</td>
      <td>{{ orders.quantity }}</td>
      <td> 
        <form action="{% url 'orders:order_detail' orders.id %}" method="get">
        <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">View</button><a href ="{% url 'orders:order_detail' orders.id%}" >
        </form>
        </td>
      <td>
        <div >
          <a href="{% url 'orders:delete_order' orders.id %}" class="px-3 py-2 text-white no-underline bg-red-700 rounded hover:bg-red-500 text-sm"> Delete</a>
         </div> 
      </td>
      
    </tr>
    {% endfor %}
    
  </table>
</div>
  
{% endblock %}