clients/urls.py
from django.urls import path

from . import views

app_name = 'client'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create_client, name='create_client'),
    path('update/<int:pk>', views.update_client, name='update_client'),
    path('client_list/', views.client_list, name='client_list'),
    path('delete/<int:pk>', views.delete_client, name='delete_client'),
    path('add/community/', views.add_community, name='add_community'),


]

core/urls.py
from django.urls import path

from core import views



app_name = 'jobs'

urlpatterns = [
    path('<int:pk>/',  views.job_detail, name='jobs'),
    path('create/', views.create_job, name='create_job'),
    path('update/<int:pk>', views.update_job, name='update_job'),
    path('job_list/', views.job_list, name='job_list'),
    path('delete/<int:pk>', views.delete_job, name='delete_job'),
    #path('schedule/view/<int:job_id>', views.job_schedule_view, name='job_schedule'),
    #path('schedule/add/<int:job_id>', views.add_job_schedule, name='add_schedule'),
    #path('schedule/update/<int:pk>', views.update_schedule, name='update_schedule'),
    #path('schedule/delete/<int:pk>', views.delete_schedule, name='delete_schedule'),
     
     
]

rest/urls.py
import statistics
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from core.views import index
from members.views import login_user, logout_user
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name ='index'),
    path('clients/', include('clients.urls')),
    path('employees/',include('employees.urls'), name ='employees'),
    path('jobs/', include('core.urls'), name ='jobs'),  
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('inventory/', include('inventory.urls'), name ='inventory'),   
    path('orders/', include('orders.urls'), name ='orders'), 
    path('maintenance/', include('maintenance.urls'), name ='maintenance'),
    

   
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.
class District(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

class Community(models.Model):
    name = models.CharField(max_length=255)
    district = models.ForeignKey(District, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Communities'
        ordering = ('name',)

    def __str__(self):
        return self.name
    

class Account(models.Model):
    type = models.CharField(max_length=255)
    def __str__(self):
        return self.type

class Client(models.Model):
    class ClientStatus(models.TextChoices):
        NEW = 'NW', _('New')
        RECURRENT = 'RC', _('Recurrent')
        REFERRAL = 'RF', _('Referral')
        THIRD_PARTY = 'TP', _('Third Party')

    name = models.CharField(max_length=255)
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    accountType = models.ForeignKey(Account, on_delete=models.CASCADE, default = 0)
    contact_email = models.CharField(max_length=255, default =0)
    contact_phone = models.CharField(max_length=255, default=0)
    billing_address = models.CharField(max_length=255, default=0)
    
    client_status = models.CharField(
        max_length=2,
        choices=ClientStatus.choices,
        default=ClientStatus.NEW,
    )
        

    # Add other fields for client details

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

clients/forms.py
from django import forms
from django.forms import FileInput, ModelForm, TextInput
from core.models import Client, Community

class ClientCreationForm(ModelForm):
    class Meta:
        model = Client
        fields = '__all__'  # Add other fields as needed


class CommunityForm(ModelForm):
    class Meta:
        model = Community
        fields = '__all__'  # Add other fields as needed

clients/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect

from clients.forms import ClientCreationForm, CommunityForm

from core.filters import ClientFilter

from clients.models import Client

from django.db.models import Sum


def detail(request, pk):
    client = get_object_or_404(Client, pk=pk)

    related_jobs = client.jobs.all()

    total_estimate= related_jobs.aggregate(Sum('estimate'))['estimate__sum'] or 0

    total_actual= related_jobs.aggregate(Sum('amount_actual'))['amount_actual__sum'] or 0

    job_instance = client.jobs.first()

    context={'related_jobs':related_jobs, 'client':client, 'total_estimate':total_estimate, 'total_actual':total_actual}

    return render(request, 'client/detail.html', context) 


def create_client(request):
    if request.method == 'POST':
        form = ClientCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('jobs:job_list')  # Redirect to the Job list page
    else:
        form = ClientCreationForm()

    return render(request, 'client/create_client.html', {'form': form})


def client_list(request):
    client_filter = ClientFilter(request.GET, queryset=Client.objects.all())
    form=client_filter.form
    clients = client_filter.qs
    context = {'clients': clients , 'form': form}
    return render(request, 'client/client_list.html', context)
   

def update_client(request, pk):
    client=Client.objects.get(id=pk)
    form = ClientCreationForm(instance=client)
    if request.method == 'POST':
        form = ClientCreationForm(request.POST, instance = client)
    context= {'form': form}
    if form.is_valid():
            form.save()
            return redirect('client:client_list')  # Redirect to the Client list page
    else:
        form = ClientCreationForm()

    return render(request, 'client/create_client.html', context)

def delete_client(request, pk):
    client=Client.objects.get(pk=pk)
    if request.method == 'POST':
        client.delete()
        return redirect('client:client_list') 
    
    context = {'item': client}
    return render(request, 'client/delete_client.html', context)


def add_community(request):
    if request.method == 'POST':
        form = CommunityForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('client:create_client')  # Redirect to the client page after successful form submission
    else:
        form = CommunityForm()
    return render(request, 'client/add_community.html', {'form': form})

clients/templates/client/add_community.html
<!-- create client-->
{% extends 'core/base.html' %}
{% load tailwind_filters %}

{% block content %}
  <h2 class="text-center mb-4 text-xl font-bold leading-none tracking-tight text-white md:text-2xl lg:text-3xl dark:text-white">Create Community</h2>

  

<div class="mx-auto w-4/12 bg-yellow-400 p-7 my-10 ">
  <form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
  
  <button class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800 mt-5" type="submit">Create/Update Client</button>
</form>
</div>

{% endblock %}

clients/templates/client/client_list.html
{% extends 'core/base.html' %}
{% load tailwind_filters %}

{% block content %}

<div class="mb-10 grid-cols-2">
<h1 class="text-white text-3xl text-center" >Client List</h1>

</div>
<div class="mt-10 grid-cols-2 text-center">
  <a href="{% url 'client:create_client' %}" class="px-6 py-3 text-white no-underline bg-emerald-700 rounded hover:emerald-700 hover:underline hover:text-blue-200 ">Create/Update Client</a>
</div>
<div class="mx-auto w-4/12 bg-yellow-400 p-7 my-10 col-3">
<form method="GET" action ="{% url 'client:client_list' %}">
  {{ form|crispy }}
<button type="submit" class="mt-5 text-white bg-red-700 hover:bg-red-800 focus:outline-none focus:ring-4 focus:ring-red-300 font-medium rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">Search</button></td>
</form>
</div>

<div class="relative overflow-x-auto">
    <table class=" table w-full text-md text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-sm text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
  
    <tr>
      <th scope="col" class="px-6 py-3">Client Name</th>
      <th scope="col" class="px-6 py-3">Location</th>
      <th scope="col" class="px-6 py-3">Client Status</th>
      <th scope="col" class="px-6 py-3">View Job</th>
      <th scope="col" class="px-6 py-3">Remove</th>
    </tr>
    {% for client in clients %}
    <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
      <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
      
      {{ client.name }}</th>
      <td>{{ client.community }}</td>s
      <td>{{ client.get_client_status_display}}</td>
      <td> 
        <form action="{% url 'client:detail' client.id%}" method="get">
        <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">View</button><a href ="{% url 'client:detail' client.id%}" >
        </form>
        </td>
      <td><div >
        <a href="{% url 'client:delete_client' client.id %}" class="px-3 py-2 text-white no-underline bg-red-700 rounded hover:bg-red-500 text-sm"> Delete</a>
       </div> 
      </td>
      
    </tr>
    {% endfor %}
    
  </table>
</div>
  
{% endblock %}

clients/templates/client/create_client.html
<!-- create client-->
{% extends 'core/base.html' %}
{% load tailwind_filters %}

{% block content %}
  <h2 class="text-center mb-4 text-xl font-bold leading-none tracking-tight text-white md:text-2xl lg:text-3xl dark:text-white">Create/Update Client</h2>

  <a href="{% url 'client:add_community'%}" class="text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Add Community</a>
  

<div class="mx-auto w-4/12 bg-yellow-400 p-7 my-10 ">
  <form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
  
  <button class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800 mt-5" type="submit">Create/Update Client</button>
</form>
</div>

{% endblock %}

clients/templates/client/delete_client.html
{% extends 'core/base.html' %}
{% load tailwind_filters %}
{% load static %}
{% block content %}

<p class="text-2xl text-white">Are you sure you want to delete "{{item}}" ?</p>

<form action="{% url 'client:delete_client' item.id %} " method ='POST' class="text-white mt-10 px-10">

    {% csrf_token %}
    
    <a href="{% url 'client:client_list' %}"class="px-3 py-2 text-white no-underline bg-emerald-700 rounded hover:bg-emerald-500 text-sm">Cancel</a>

    <input class="px-3 py-2 text-white no-underline bg-red-800 rounded hover:bg-red-600 text-sm" type="submit" name="Confirm">


</form>


{% endblock %}

clients/templates/client/detail.html
{% extends 'core/base.html'%}

{% block title %} {{client.name}} {% endblock %}

{% block content %}

<div class="grid grid-cols-5 gap-6">

    <div class="col-span-2">
        <p></p>
    </div>
    <div class="col-span-3 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-4xl">Client: {{client.name}}</h1>
        <p class="text-gray-500 pt-5"><strong> Location: </strong>{{client.community}}</p>
        <p class="text-gray-500 pt-5"><strong> Account Type: </strong>{{client.accountType}}</p>
        <p class="text-gray-500 pt-5"><strong> Email: </strong>{{client.contact_email}}</p>
        <p class="text-gray-500 pt-5"><strong> Phone: </strong>{{client.contact_phone}}</p>
        <p class="text-gray-500 pt-5"><strong> Jobs: </strong>{{client.jobs.count}}</p>
        <div class = "grid grid-cols-3 gap3">
            {% for related_jobs in related_jobs %}
                
                <div>
                    <a href="{% url 'jobs:jobs' related_jobs.id %}" >
                        <div class="p-6 bg-white rounded-b-xl">
                            <p class = "text-gray-600"">{{related_jobs.title}}</p>
                            <p class="text-gray-600">{{related_jobs.amount}}</p>
                           
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
        <p class="text-gray-500 pt-5"><strong> Total Estimated Cost: $</strong>{{total_estimate}}</p>
        <p class="text-gray-500 pt-5"><strong> Amount Made: $</strong>{{total_actual}}</p>
        <div class ="mt-10">
        <a href="{% url 'client:update_client' client.id%}"
          class="px-3 py-2 text-white no-underline bg-emerald-700 rounded hover:bg-emerald-500 text-sm ">Update Client</a>
        </div>
        <div class ="mt-10" >
            <a href="{% url 'client:delete_client' client.id %}" class="px-3 py-2 text-white no-underline bg-red-700 rounded hover:bg-red-500 text-sm"> Delete</a>
           </div> 
    </div>
    
</div>

{% endblock %} 