Inventory/urls.py
# urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('add/brand/', add_brand, name='add_brand'),
    path('add/battery/', add_battery, name='add_battery'),
    path('add/inverter/', add_inverter, name='add_inverter'),
    path('add/panel/', add_panel, name='add_panel'),
    path('add/brand/<int:pk>/', update_brand, name='update_brand'),
    path('add/battery/<int:pk>/', update_battery, name='update_battery'),
    path('add/panel/<int:pk>/', update_panel, name='update_panel'),
    path('add/inverter/<int:pk>/', update_inverter, name='update_inverter'),
    path('inventory', inventory_list, name='inventory_list'),
    path('delete/battery/<int:pk>/', delete_battery, name='delete_battery'),
    path('delete/panel/<int:pk>/', delete_panel, name='delete_panel'),
    path('delete/inverter/<int:pk>/', delete_inverter, name='delete_inverter'),
    path('delete/brand/<int:pk>/', delete_brand, name='delete_brand')
    # other URL patterns
]

clients/urls.py
from django.urls import path

from . import views

app_name = 'client'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create_client, name='create_client'),
    path('update/<int:pk>', views.update_client, name='update_client'),
    path('client_list/', views.client_list, name='client_list'),
    path('delete/<int:pk>', views.delete_client, name='delete_client'),
    path('add/community/', views.add_community, name='add_community'),


]

core/urls.py
from django.urls import path

from core import views



app_name = 'jobs'

urlpatterns = [
    path('<int:pk>/',  views.job_detail, name='jobs'),
    path('create/', views.create_job, name='create_job'),
    path('update/<int:pk>', views.update_job, name='update_job'),
    path('job_list/', views.job_list, name='job_list'),
    path('delete/<int:pk>', views.delete_job, name='delete_job'),
    #path('schedule/view/<int:job_id>', views.job_schedule_view, name='job_schedule'),
    #path('schedule/add/<int:job_id>', views.add_job_schedule, name='add_schedule'),
    #path('schedule/update/<int:pk>', views.update_schedule, name='update_schedule'),
    #path('schedule/delete/<int:pk>', views.delete_schedule, name='delete_schedule'),
     
     
]

employees/urls.py
from django.urls import path

from . import views

from .views import *

app_name = 'employees'

urlpatterns = [
     path('<int:pk>/', views.detail, name='detail'),
     path('update/<int:pk>/', update_employee, name='update_employee'),
     path('create/', create_employee, name='create_employee'),
     path('employee_list/', employee_list, name='employee_list'),
     path('delete/<int:pk>/', delete_employee, name='delete_employee'),
]

maintenance/urls.py
from django.urls import path

from maintenance.views import *  

# urls.py

app_name ='maintenance'

urlpatterns = [
    path('view/<int:job_id>/', job_schedule_view, name='job_schedule'),
    path('add/<int:job_id>', add_job_schedule, name='add_schedule'),
    path('update/<int:schedule_id>/', update_job_schedule, name='update_schedule'),
    path('delete/<int:schedule_id>/', delete_job_schedule, name='delete_schedule'),
    path('create/', create_job_schedule, name='create_schedule'),

]

rest/urls.py
import statistics
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from core.views import index
from members.views import login_user, logout_user
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name ='index'),
    path('clients/', include('clients.urls')),
    path('employees/',include('employees.urls'), name ='employees'),
    path('jobs/', include('core.urls'), name ='jobs'),  
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('inventory/', include('inventory.urls'), name ='inventory'),   
    path('orders/', include('orders.urls'), name ='orders'), 
    path('maintenance/', include('maintenance.urls'), name ='maintenance'),
    

   
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from datetime import date, timedelta
from clients.models import Client
from clients.models import Community
from django.utils.translation import gettext_lazy as _


# Create your models here.

class System(models.Model):
    title = models.CharField(max_length=255)
    cost = models.IntegerField(default=0)
    size = models.IntegerField(default=0)
    instock = models.BooleanField(default=False)
    

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title
    
class Payment(models.Model):
    type= models.CharField(max_length=255)

    class Meta:
        ordering = ('type',)
    
    def __str__(self):
        return self.type

class Picture(models.Model):
    picture = models.ImageField(upload_to='job_images/', blank=True, null=True)  

    def __str__(self):
        return self.picture.url
    
class Document(models.Model):
    document = models.FileField(upload_to='job_documents/', blank=True, null=True) 

    def __str__(self):
        return self.document.url



class Job(models.Model):

    class JobProgress(models.TextChoices):
        CONSULTATION = 'CS', _('Consultation')
        IN_PROGRESS = 'IP', _('In progress')
        FINISHED = 'FN', _('Finished')
        CLOSED = 'CL', _('Closed')
    
    class JobRisk(models.TextChoices):
        HIGH = 'HI', _('High')
        MEDIUM = 'MI', _('Medium')
        LOW = 'LO', _('Low')

    class MaintenanceType(models.TextChoices):
        YEARLY = 'YR', _('Yearly')
        BIANNUAL = 'BA', _('Bi Annual')
       
    class PaymentType(models.TextChoices):
        DIRECT_PURCHASE='DP', _('Direct Purchase')
        LEASE = 'LS', _('Lease')

   
        
    title = models.CharField(max_length=255)
    job_progress = models.CharField(
        max_length=2,
        choices=JobProgress.choices,
        default=JobProgress.CONSULTATION,
    )   
    job_risk = models.CharField(
        max_length=2,
        choices=JobRisk.choices,
        default=JobRisk.LOW,
    ) 
    


    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='jobs')
    location = models.ForeignKey(Community, on_delete=models.CASCADE)
    system = models.ForeignKey(System, on_delete=models.CASCADE)
    employees = models.ManyToManyField('Employee', related_name='jobs')
    #lease = models.BooleanField(default=False)
    payment_type = models.CharField(
        max_length=2,
        choices=PaymentType.choices,
        default=PaymentType.DIRECT_PURCHASE
    ) 

    payment = models.ForeignKey(Payment, on_delete=models.CASCADE)
    job_progress = models.CharField(
        max_length=2,
        choices=JobProgress.choices,
        default=JobProgress.CONSULTATION,
    )   
    estimate = models.DecimalField(max_digits=10, decimal_places=2)
    amount_actual = models.DecimalField(max_digits=10, decimal_places=2, default=0, null=True, blank=True)
    start_date = models.DateField()
    actual_end_date = models.DateField(default=date.today, blank=True, null=True)
    duration = models.FloatField(default=0)
    maintenance_type = models.CharField(
        max_length=2,
        choices=MaintenanceType.choices,
        default=MaintenanceType.YEARLY,
    )   
    notes=models.TextField(default='none', blank=True, null=True)
    documents = models.ManyToManyField(Document, blank=True, related_name="job_doc") 
    images = models.ManyToManyField(Picture, blank=True, related_name="job_img")
    display_image= models.ImageField(upload_to='job_images/', default = 'job_images/rest_logo.jpg', blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    # Add other fields for job details
    class Meta:
        ordering = ('title',)
    @property
    def end_date(self):
        return self.start_date + timedelta(days=self.duration)
    def __str__(self):
        return self.title
    def profitability(self):
        return self.amount_actual - self.estimate
    
    def on_time(self):
        return (self.actual_end_date - self.start_date).days 
    
    
class Employee(models.Model):
    class EmployeeStatus(models.TextChoices):
        CURRENT = 'CU', _('Current')
        PASTEMPLOYEE = 'PE', _('Past Employee')
        

    employee_status= models.CharField(
        max_length=2,
        choices=EmployeeStatus.choices,
        default=EmployeeStatus.CURRENT,
    )  
    name = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    address = models.CharField(max_length=255, default='none', blank=True,null=True)
    dob=models.DateField( default=date.today)
    email = models.EmailField(max_length=255, blank=True, null=True)
    wage = models.DecimalField(max_digits=10, decimal_places=2)
    images = models.ImageField(upload_to='employee_images/', default='employee_images/human_placeholder.png', blank=True, null=True)
    # Add other fields for employee details

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    
class Compensation(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    employee=models.ForeignKey(Employee, on_delete=models.CASCADE)
    daysWorked = models.DecimalField(max_digits=5, decimal_places=2)
    compensation = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        ordering = ('job',)

    def __str__(self):
        return self.job + self.employee
    

clients/forms.py
from django import forms
from django.forms import FileInput, ModelForm, TextInput
from core.models import Client, Community

class ClientCreationForm(ModelForm):
    class Meta:
        model = Client
        fields = '__all__'  # Add other fields as needed


class CommunityForm(ModelForm):
    class Meta:
        model = Community
        fields = '__all__'  # Add other fields as needed

Inventory/views.py
from django.shortcuts import render, redirect
from core.filters import BatteryFilter , PanelFilter, InverterFilter, BrandFilter
from inventory.forms import BatteryForm, PanelForm, InverterForm, BrandForm
from .models import Battery, Panel, Inverter, Brand
from django.contrib import messages

# Create your views here.



def add_battery(request):
    
    if request.method == 'POST':
        battery_form = BatteryForm(request.POST)
        if battery_form.is_valid():

            battery_form.save()
            return redirect('add_battery')  # Redirect to the homepage after successful form submission
        else:
            messages.success(request,("There was an error, serial number already exists"))
            return redirect('add_battery') 
    else:
        battery_filter = BatteryFilter(request.GET, queryset=Battery.objects.all())
        search_form=battery_filter.form
        batterys = battery_filter.qs
        battery_form = BatteryForm()
        context = {'batterys': batterys, 'search_form': search_form, 'battery_form': battery_form}
        
        return render(request, 'battery_list.html', context)
    
def update_battery(request, pk):
    battery=Battery.objects.get(pk=pk)
    form = BatteryForm(instance=battery)
    if request.method == 'POST':
        form = BatteryForm(request.POST, request.FILES, instance=battery)
    context= {'form': form}
    if form.is_valid():
            form.save()
            return redirect('add_battery')  # Redirect to the panel list page
    else:
        form = BatteryForm()
    
    return render(request, 'battery_update.html', context)

def delete_battery(request, pk):
    battery=Battery.objects.get(pk=pk)
    if request.method == 'POST':
        battery.delete()
        return redirect('add_battery') 
    
    context = {'item': battery}
    return render(request, 'battery_delete.html', context)

       


def add_panel(request):
    if request.method == 'POST':
        panel_form = PanelForm(request.POST)
        if panel_form.is_valid():
            panel_form.save()
            return redirect('add_panel')  # Redirect to the panel page after successful form submission
        else:
            messages.success(request,("There was an error, serial number already exists"))
            return redirect('add_panel') 
    else:
        panel_filter = PanelFilter(request.GET, queryset=Panel.objects.all())
        search_form=panel_filter.form
        panels = panel_filter.qs
        panel_form = PanelForm()
        context = {'panels': panels, 'search_form': search_form, 'panel_form': panel_form}
        
        return render(request, 'panel_list.html', context)

def update_panel(request, pk):
    panel=Panel.objects.get(pk=pk)
    form = PanelForm(instance=panel)
    if request.method == 'POST':
        form = PanelForm(request.POST, request.FILES, instance=panel)
    context= {'form': form}
    if form.is_valid():
            form.save()
            return redirect('add_panel')  # Redirect to the panel list page
    else:
        form = PanelForm()
    
    return render(request, 'panel_update.html', context)

def delete_panel(request, pk):
    panel=Panel.objects.get(pk=pk)
    if request.method == 'POST':
        panel.delete()
        return redirect('add_panel') # Redirect to the panel list page 
    
    context = {'item': panel}
    return render(request, 'panel_delete.html', context)


def add_inverter(request):
    if request.method == 'POST':
        inverter_form = InverterForm(request.POST)
        if inverter_form.is_valid():
            inverter_form.save()
            return redirect('add_inverter')  # Redirect to the inverter page after successful form submission
        else:
            messages.success(request,("There was an error, serial number already exists"))
            return redirect('add_inverter') 
    else:
        inverter_filter = InverterFilter(request.GET, queryset=Inverter.objects.all())
        search_form=inverter_filter.form
        inverters = inverter_filter.qs
        inverter_form = InverterForm()
        context = {'inverters': inverters, 'search_form': search_form, 'inverter_form': inverter_form}
        
        return render(request, 'inverter_list.html', context)

def update_inverter(request, pk):
    job=Inverter.objects.get(pk=pk)
    form = InverterForm(instance=job)
    if request.method == 'POST':
        form = InverterForm(request.POST, request.FILES, instance=job)
    context= {'form': form}
    if form.is_valid():
            form.save()
            return redirect('add_inverter')  # Redirect to the inveretr list page
    else:
        form = InverterForm()
    
    return render(request, 'inverter_update.html', context)

def delete_inverter(request, pk):
    inverter=Inverter.objects.get(pk=pk)
    if request.method == 'POST':
        inverter.delete()
        return redirect('add_inverter') # Redirect to the inverter list page 
    
    context = {'item': inverter}
    return render(request, 'inverter_delete.html', context)


def inventory_list(request):
    batteries= Battery.objects.all()
    panels= Panel.objects.all()
    inverters= Inverter.objects.all()
    in_use_batteries = Battery.objects.filter(in_use=True)
    available_batteries = Battery.objects.filter(in_use=False)
    in_use_panels = Panel.objects.filter(in_use=True)
    available_panels= Panel.objects.filter(in_use=False)
    in_use_inverters = Inverter.objects.filter(in_use=True)
    available_inverters= Inverter.objects.filter(in_use=False)

    context = {'batteries': batteries,'in_use_batteries':in_use_batteries, 'available_batteries':available_batteries, 'panels': panels, 'in_use_panels':in_use_panels,'available_panels':available_panels,'inverters': inverters, 'in_use_inverters':in_use_inverters, 'available_inverters':available_inverters}
    return render(request, 'inventory_list.html', context)


def add_brand(request):
    
    if request.method == 'POST':
        brand_form = BrandForm(request.POST)
        if brand_form.is_valid():

            brand_form.save()
            return redirect('add_brand')  # Redirect to the homepage after successful form submission
        else:
            messages.success(request,("There was an error, serial number already exists"))
            return redirect('add_brand') 
    else:
        brand_filter = BrandFilter(request.GET, queryset=Brand.objects.all())
        search_form=brand_filter.form
        brands = brand_filter.qs
        brand_form = BrandForm()
        context = {'brands': brands, 'search_form': search_form, 'brand_form': brand_form}
        
        return render(request, 'brand_list.html', context)
    
def update_brand(request, pk):
    brand=Brand.objects.get(pk=pk)
    form = BrandForm(instance=brand)
    if request.method == 'POST':
        form = BrandForm(request.POST, request.FILES, instance=brand)
    context= {'form': form}
    if form.is_valid():
            form.save()
            return redirect('add_brand')  # Redirect to the panel list page
    else:
        form = BrandForm()
    
    return render(request, 'brand_update.html', context)

def delete_brand(request, pk):
    brand=Brand.objects.get(pk=pk)
    if request.method == 'POST':
        brand.delete()
        return redirect('add_brand') 
    
    context = {'item': brand}
    return render(request, 'brand_delete.html', context)

core/templates/core/base.html
{% load static %}
{% load static tailwind_tags %}

<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        {% tailwind_css %}
        
        <style>
            .hidden-form {
              display: none;
            }
        </style>

<script>
    document.getElementById("show-form-button").addEventListener("click", function() {
        var form = document.getElementById("search_form");
        form.classList.remove("hidden-form");
    });

    
    document.getElementById("close-form-button").addEventListener("click", function() {
        var form = document.getElementById("my-form");
        form.classList.add("hidden-form");
    });
</script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
      
       
        <link rel="stylesheet" href="{% static 'rest/css/style.css' %}">  
            <title>{% block title %}{%endblock%}</title>
    </head>

    <body class="flex flex-col h-screen bg-gradient-to-r from-slate-900 to-slate-700">
        <nav class="py-6 px-6 flex justify-between items-center border-b border-grey-200 bg-emerald-700">
            <a  class="text-lg font-semibold" href="/"><img src="{% static 'rest/img/rest_logo.jpg' %}" alt="HTML tutorial" style="width:42px;height:42px;">Rest LTD</a>
            
            <div class="space-x-6 text-white">
                {% if user.is_authenticated %}
                    <a href="{% url 'admin:index' %}" class="rounded-xl px-6 py-3 text-lg font-semibold hover:text-rose-800 hover:bg-white">Admin</a>
                    <a href="{% url 'client:client_list' %}" class="rounded-xl px-6 py-3 text-lg font-semibold hover:text-rose-800 hover:bg-white">Clients</a>
                    <a href="{% url 'employees:employee_list' %}" class="rounded-xl px-6 py-3 text-lg font-semibold hover:text-rose-800 hover:bg-white">Employees</a>
                    <a href="{% url 'jobs:job_list' %}" class="rounded-xl px-6 py-3 text-lg font-semibold hover:text-rose-800 hover:bg-white">Jobs</a>
                    <a href="{% url 'maintenance:create_schedule' %}" class="rounded-xl px-6 py-3 text-lg font-semibold hover:text-rose-800 hover:bg-white">Maintenance</a>
                    <div class="dropdown">
                        <button class="dropbtn">Inventory</button>
                        <div class="dropdown-content">
                          <a href="{% url 'inventory_list' %}">Inventory Summary</a>
                          <a href="{% url 'add_battery' %}">Batteries</a>
                          <a href="{% url 'add_panel' %}">Panels</a>
                          <a href="{% url 'add_inverter' %}">Inverters</a>
                          <a href="{% url 'add_brand' %}">Brands</a>
                        </div>
                      </div>
                {% endif %}
                {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}" class="rounded-xl px-6 py-3 font-semibold hover:text-white-500 bg-teal-500 text-white  hover:bg-teal-700">Log Out</a>
                {% else %}
                    <a href="{% url 'login' %}" class="rounded-xl px-6 py-3 font-semibold hover:text-white-500 bg-teal-500 text-white  hover:bg-teal-700">Log In</a>
                {% endif %}
            </div>
        
        </nav>
        <div class="flex-grow px-6 py-6">
            {% block content %}
            {% endblock %} 
        </div>

        <footer class="py-6 px-6 sticky top-[100vh] justify-between bg-gradient-to-r from-slate-900 to-slate-700 ">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>
                <a href="https://www.linkedin.com/in/travishalls/" class="text-lg text-gray-500">Developed by Travis Halls</p>

            </div>
        </footer>
    </body>




</html>

core/templates/core/client.html
{% extends 'core/base.html'%}

{% block title %} Clients {% endblock %}

{% block content %}
<h1>The client front page</h1>

{% endblock %} 

core/templates/core/employee.html
{% extends 'core/base.html'%}

{% block title %}Employees {% endblock %}

{% block content %}
<h1>Employees front page</h1>

{% endblock %} 

core/templates/core/inventory.html
{% extends 'core/base.html'%}

{% block title %} Inventory {% endblock %}

{% block content %}
<h1>Inventory front page</h1>

{% endblock %} 

core/templates/core/job_detail.html
{% extends 'core/base.html'%}

{% block title %} {{job.title}} {% endblock %}

{% block content %}

<div class="grid grid-cols-5 gap-6">

    <div class="col-span-2">
        <img src="{{job.images.url}}">
    </div>
    <div class="col-span-3 p-6 bg-gray-100 rounded-xl" alt = "{{job.title}}">
        <h1 class="mb-6 text-4xl">{{job.title}}</h1>
        <p class="text-gray-500 mt-2"><strong> Client: </strong>{{job.client}}</p>
        <p class="text-gray-500 mt-2"><strong> Progress: </strong>{{job.get_job_progress_display}}</p>
        <p class="text-gray-500 mt-2"><strong> Job Risk: </strong>{{job.get_job_risk_display}}</p>
        <p class="text-gray-500 mt-2"><strong> Location: </strong>{{job.location}}</p>
        <p class="text-gray-500 mt-2"><strong> System: </strong>{{job.system}}</p>
        <p class="text-gray-500 mt-2"><strong> Employees: </strong> 
        {% for employee in employees%}

        <li><a href="{% url 'employees:detail' employee.id%}">{{employee.name}}</a></li>
          
        {% endfor %}
        
        <p class="text-gray-500 mt-2"><strong> Start Date: </strong>{{job.start_date}}</p>
        <p class="text-gray-500 mt-2"><strong> Estimated end Date: </strong>{{job.end_date}}</p>

    <div class = "">
                  
             
                <div>
                    <a href="#" >
                        <div class="cols-span-2 p-6 bg-white rounded-b-xl">
                            <h2> Batteries in Use</h2>
                            {% for battery in batteries %}
                            
                                <p>
                                <li>
                                   {{ battery}}</p>
                                </li>
                                </p>
                            {% endfor %}                     
                        </div>
                    </a>
                </div>
                <div>
                    <a href="#" >
                        <div class="cols-span-2 p-6 bg-white rounded-b-xl">
                            <h2> Panels in Use</h2>
                            {% for panel in panels %}
                            
                                <p>
                                <li>
                                   {{ panel}}</p>
                                </li>
                                </p>
                            {% endfor %}                     
                        </div>
                    </a>
                </div>
                <div>
                    <a href="#" >
                        <div class="cols-span-2 p-6 bg-white rounded-b-xl">
                            <h2> Inverters in Use</h2>
                            {% for inverter in inverters %}
                            
                                <p>
                                <li>
                                   {{ inverter}}</p>
                                </li>
                                </p>
                            {% endfor %}                     
                        </div>
                    </a>
                </div>
            
        </div>
        <h2 class="text-gray-500 mt-2"><strong>Notes: </strong> </h2>
        <div class="cols-span-2 p-6 bg-white rounded-b-xl">
            <p>{{job.notes}}</p>
            
        </div>
        <p class="text-gray-500 pt-6"><strong> Completed On Time ? : </strong>{{job.on_time}} days overdue</p>
        <p class="text-gray-500 pt-6"><strong> Estimated Cost : $</strong>{{job.estimate}}</p>
        <p class="text-gray-500 pt-6"><strong> Deposit : strong>{{job.payment}}</p>
        <p class="text-gray-500 pt-6"><strong> Actual Cost : $</strong>{{job.amount_actual}}</p>
        <p class="text-gray-500 pt-6"><strong> Profitability : $</strong>{{job.profitability}}</p>
        <p class="text-gray-500 pt-6"><strong> Maintenance : </strong>{{job.get_maintenance_type_display }}</p>
        <div class="mt-10">
            <a href="{% url 'jobs:update_job' job.id%}"
            class="px-3 py-2 text-white no-underline bg-emerald-700 rounded hover:bg-emerald-500 text-sm ">Update Job</a>
          </div>
          <div class="mt-10">
            <a href="{% url 'maintenance:job_schedule' job.id%}"
            class="px-3 py-2 text-white no-underline bg-emerald-700 rounded hover:bg-emerald-500 text-sm ">Shceduled Maintenance</a>
          </div>

          <div class=" mt-10 ">
            <a href="{% url 'jobs:delete_job' job.id %}"  class="px-3 py-2 text-white no-underline bg-red-700 rounded hover:bg-red-500 text-sm"> Delete</a>
           </div> 
    </div>
    
</div>

{% endblock %} 

core/templates/core/job_list.html
{% extends 'core/base.html' %}
{% load tailwind_filters %}

{% block content %}

<div class="mb-10 grid-cols-2">
<h1 class="text-white text-3xl text-center" >Job List</h1>

</div>
<div class="mt-10 grid-cols-2 text-center">
  <a href="{% url 'jobs:create_job' %}" class="px-6 py-3 text-white no-underline bg-emerald-700 rounded hover:emerald-700 hover:underline hover:text-blue-200 ">Add new Job</a>
</div>
<div class="mx-auto w-4/12 bg-yellow-400 p-7 my-10 col-3">
<form method="GET" action ="{% url 'jobs:job_list' %}">
  {{ form|crispy }}
<button type="submit" class="mt-5 text-white bg-red-700 hover:bg-red-800 focus:outline-none focus:ring-4 focus:ring-red-300 font-medium rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">Search</button></td>
</form>
</div>

<div class="relative overflow-x-auto">
    <table class=" table w-full text-md text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-sm text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
  
    <tr>
      <th scope="col" class="px-6 py-3">Job Title</th>
      <th scope="col" class="px-6 py-3">Job Location</th>
      <th scope="col" class="px-6 py-3">Job Amount</th>
      <th scope="col" class="px-6 py-3">Start Date</th>
      <th scope="col" class="px-6 py-3">View Job</th>
      <th scope="col" class="px-6 py-3">Remove</th>
    </tr>
    {% for job in jobs %}
    <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
      <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
      
      {{ job.title }}</th>
      <td>{{ job.location }}</td>
      <td>{{ job.amount }}</td>
      <td>{{ job.start_date}}</td>
      <td> 
        <form action="{% url 'jobs:jobs' job.id%}" method="get">
        <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">View</button><a href ="{% url 'jobs:jobs' job.id%}" >
        </form>
        </td>
        <td>
          <div>
            <a href="{% url 'jobs:delete_job' job.id %}"  class="px-3 py-2 text-white no-underline bg-red-700 rounded hover:bg-red-500 text-sm"> Delete</a>
           </div> 
        </td>
      
    </tr>
    {% endfor %}
    
  </table>
</div>
  
{% endblock %}