core/urls.py
from django.urls import path

from core import views



app_name = 'jobs'

urlpatterns = [
    path('<int:pk>/',  views.job_detail, name='jobs'),
    path('create/', views.create_job, name='create_job'),
    path('update/<int:pk>', views.update_job, name='update_job'),
    path('job_list/', views.job_list, name='job_list'),
    path('delete/<int:pk>', views.delete_job, name='delete_job'),
    #path('schedule/view/<int:job_id>', views.job_schedule_view, name='job_schedule'),
    #path('schedule/add/<int:job_id>', views.add_job_schedule, name='add_schedule'),
    #path('schedule/update/<int:pk>', views.update_schedule, name='update_schedule'),
    #path('schedule/delete/<int:pk>', views.delete_schedule, name='delete_schedule'),
     
     
]

employees/urls.py
from django.urls import path

from . import views

from .views import *

app_name = 'employees'

urlpatterns = [
     path('<int:pk>/', views.detail, name='detail'),
     path('update/<int:pk>/', update_employee, name='update_employee'),
     path('create/', create_employee, name='create_employee'),
     path('employee_list/', employee_list, name='employee_list'),
     path('delete/<int:pk>/', delete_employee, name='delete_employee'),
]

rest/urls.py
import statistics
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from core.views import index
from members.views import login_user, logout_user
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name ='index'),
    path('clients/', include('clients.urls')),
    path('employees/',include('employees.urls'), name ='employees'),
    path('jobs/', include('core.urls'), name ='jobs'),  
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('inventory/', include('inventory.urls'), name ='inventory'),   
    path('orders/', include('orders.urls'), name ='orders'), 
    path('maintenance/', include('maintenance.urls'), name ='maintenance'),
    

   
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employees/forms.py
# employees/forms.py
from django import forms
from django.forms import FileInput, ModelForm, TextInput
from core.models import Employee

class EmployeeUpdateForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['name', 'title', 'email','wage','images' ]  # Add other fields as needed
        images = forms.ImageField() 
        widgets = {
            'name': TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px; border: 2px solid red;  border-radius: 5px;',
                'placeholder': 'Name'
                }),
            'title': TextInput(attrs={
                'class': "form-control", 
                'style': 'max-width: 300px;',
                'placeholder': 'Title'
                }),
            'email': TextInput(attrs={
                'class': "form-control", 
                'style': 'max-width: 300px;',
                'placeholder': 'Email'
                }),
            'wage': TextInput(attrs={
                'class': "form-control", 
                'style': 'max-width: 300px;',
                'placeholder': 'Wage'
                }),
            'images': TextInput(attrs={
                'class': "form-control", 
                'style': 'max-width: 300px;',
                'placeholder': 'Images'
                }),
            

        }

class EmployeeCreationForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['employee_status','name', 'title','dob','address', 'email','wage','images' ]  # Add other fields as needed
        images = forms.ImageField() 
        widgets = {
            'current': forms.CheckboxInput(attrs={
                'class': 'form-check-input',
                'style': 'margin-top: 10px; margin-bottom: 10px;',
                'labels': 'Current Employee?'
                }),
            'name': TextInput(attrs={
                'class': "form-control",
                'style': 'mt-5 max-width: 300px; ',
                'placeholder': 'Name'
                }),
            'title': TextInput(attrs={
                'class': "form-control", 
                'style': 'mt-5 max-width: 300px;',
                'placeholder': 'Title'
                }),
            'email': TextInput(attrs={
                'class': "form-control", 
                'style': 'mt-5 max-width: 300px;',
                'placeholder': 'Email'
                }),
            'wage': TextInput(attrs={
                'class': "form-control", 
                'style': 'mt-5 max-width: 300px;',
                'placeholder': 'Wage'
                }),
            'images': FileInput(attrs={
                'id' : 'image_field' , 
                'style': 'height: 50px ;  color: white; '
                    })
            
            

        }

employees/views.py
from django.shortcuts import render, get_object_or_404, redirect

from employees.forms import EmployeeCreationForm

from core.filters import EmployeeFilter

# Create your views here.
from core.models import Employee , Job

# Employee Details View
def detail(request, pk):
    employee = get_object_or_404(Employee, pk=pk)

    related_jobs = employee.jobs.all()

    job_instance = employee.jobs.first()

    if job_instance:
        total_job_time = sum(job.duration for job in related_jobs)
        job_payments = [(job.title, int(job.duration) * employee.wage) for job in related_jobs]
    else:
        total_job_time = 0
        job_payments = [('no jobs', total_job_time) for job in related_jobs]

   # job_payment= employee.wage

    amount_paid = float(employee.wage) * total_job_time

    #job_instance = client.jobs.first()

   

    #return render(request, 'client/detail.html', {'related_jobs':related_jobs,'job_cost':job_cost, 'client':client}) 

    return render(request, 'core/employee_detail.html', {'employee':employee, 'related_jobs':related_jobs, 'amount_paid':amount_paid, 'job_payments':job_payments})


# employees/views.py



def employee_list(request):
    employee_filter = EmployeeFilter(request.GET, queryset=Employee.objects.all())
    form=employee_filter.form
    employees = employee_filter.qs
    return render(request, 'employees/employee_list.html', {'employees': employees, 'form': form})

def create_employee(request):
    if request.method == 'POST':
        form = EmployeeCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('employees:employee_list')  # Redirect to the employee list page
    else:
        form = EmployeeCreationForm()

    return render(request, 'employees/create_employee.html', {'form': form})


def update_employee(request, pk):
    job=Employee.objects.get(pk=pk)
    form = EmployeeCreationForm(instance=job)
    if request.method == 'POST':
        form = EmployeeCreationForm(request.POST, request.FILES, instance=job)
    context= {'form': form}
    if form.is_valid():
            form.save()
            return redirect('employees:employee_list')  # Redirect to the employee list page
    else:
        form = EmployeeCreationForm()
    
    return render(request, 'employees/create_employee.html', context)


def delete_employee(request, pk):
    employee=Employee.objects.get(pk=pk)
    if request.method == 'POST':
        employee.delete()
        return redirect('employees:employee_list') 
    
    context = {'item': employee}
    return render(request, 'employees/delete_employee.html', context)

employees/templates/employees/create_employee.html
<!-- employees/templates/employees/create_employee.html -->
{% extends 'core/base.html' %}
{% load tailwind_filters %}

{% block content %}
  <h2 class="text-center mb-4 text-xl font-bold leading-none tracking-tight text-white md:text-2xl lg:text-3xl dark:text-white">Create/Update Employee</h2>
  
  <div class="mx-auto w-4/12 bg-yellow-400 p-7 my-10 ">
  <form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
  
  <button class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800 mt-5" type="submit">Create/Update Employee</button>
</form>
</div>
{% endblock %}

employees/templates/employees/delete_employee.html
{% extends 'core/base.html' %}
{% load tailwind_filters %}
{% load static %}
{% block content %}

<p class="text-2xl text-white">Are you sure you want to delete "{{item}}" ?</p>

<form action="{% url 'employees:delete_employee' item.id %} " method ='POST' class="text-white mt-10 px-10">

    {% csrf_token %}
    
    <a href="{% url 'employees:employee_list' %}"class="px-3 py-2 text-white no-underline bg-emerald-700 rounded hover:bg-emerald-500 text-sm">Cancel</a>

    <input class="px-3 py-2 text-white no-underline bg-red-800 rounded hover:bg-red-600 text-sm" type="submit" name="Confirm">


</form>


{% endblock %}

employees/templates/employees/employee_list.html
{% extends 'core/base.html' %}
{% load tailwind_filters %}

{% block content %}

<div class="mb-10 grid-cols-2">
<h1 class="text-white text-3xl text-center" >Employee List</h1>

</div>
<div class="mt-10 auto-cols-max text-left">
  <div class ="text-center">
     <a href="{% url 'employees:create_employee' %}" class="px-6 py-3 text-white no-underline bg-emerald-700 rounded hover:emerald-700 hover:underline hover:text-blue-200 ">Add new Employee</a>
  </div>
  <div class="mx-auto w-4/12 bg-yellow-400 p-7 my-10 col-3">
      <form method="GET" action ="{% url 'employees:employee_list' %}">
      {{ form|crispy }}
      <button type="submit" class="mt-5 text-white bg-red-700 hover:bg-red-800 focus:outline-none focus:ring-4 focus:ring-red-300 font-medium rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">Search</button></td>
      </form>
  </div>
</div>

<div class="relative overflow-x-auto">
    <table class=" table w-full text-md text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-sm text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
  
    <tr>
      <th scope="col" class="px-6 py-3">Employee Name</th>
      <th scope="col" class="px-6 py-3">Employee Title</th>
      <th scope="col" class="px-6 py-3">View Profile</th>
      <th scope="col" class="px-6 py-3">Remove</th>
    </tr>
    {% for employee in employees %}
    <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
      <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
      
      {{ employee.name }}</th>
      <td>{{ employee.title }}</td>
      <td> 
        <form action="{% url 'employees:detail' employee.id%}" method="get">
        <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">View</button><a href ="{% url 'employees:detail' employee.id%}" >
        </form>
        </td>
      <td>
        <div >
          <a href="{% url 'employees:delete_employee' employee.id %}" class="px-3 py-2 text-white no-underline bg-red-700 rounded hover:bg-red-500 text-sm"> Delete</a>
         </div> 
      </td>
      
    </tr>
    {% endfor %}
    
  </table>
</div>
  
{% endblock %}

employees/templates/employees/update_employee.html
<!-- employees/templates/employees/update_employee.html -->
print("Employee ID: {{employee.id}}") 
{% if employee.id %}
<form method="post" action="{% url 'employees:update_employee' employee.id %}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Update</button>
</form>
{% else %}
  <p>Employee ID is not available.</p>
{% endif %}